name: Run test.sh on Push

on:
  push:
    branches:
      - main
    paths:
      - 'project/**'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test script
        run: |
          chmod +x ./project/test.sh
          ./project/test.sh
